# Generated by Django 5.1.4 on 2025-01-15 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropoutsummary',
            name='student',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='dropout_summary', to='account.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
