# Generated by Django 5.1.4 on 2025-01-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_dropoutsummary_student_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropoutsummary',
            name='is_dropout',
            field=models.BooleanField(default=True),
        ),
    ]
