from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('add/', views.create_student, name='add'),
    path('login/', views.login_view, name='login'),
    path('register/',views.register,name='register'),
    path('category/',views.get_categories,name='category'),
    path('profile/',views.profile,name='profile'),
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('update-profile/',views.update_profile,name='update_profile'),
    path('delete-profile/',views.delete_profile,name='delete_profile'),
    path('change-password/',views.change_password,name='change_password'),
    path('forgot-password/',views.forgot_password,name='forgot_password'),
    path('reset-password/',views.reset_password,name='reset_password'),
    path('students/', views.get_students, name='student'),
    #path('students/<int:id>/', views.get_student, name='student'),
    path('students/create/', views.create_student, name='create_student'),
    #path('students/update/<int:id>/', views.update_student, name='update_student'),
    #path('students/delete/<int:id>/', views.delete_student, name='delete_student'),
    path('students/search/', views.search_student, name='search_student'),
    path('students/filter/', views.filter_student, name='filter_student'),
    path('students/sort/', views.sort_student, name='sort_student'),
    path('students/export/', views.export_students, name='export_students'),
    path('students/import/', views.import_students, name='import_students'),
    path('students/upload/', views.upload_students, name='upload_students'),
    path('students/download/', views.download_students, name='download_students'),
    path('reports/', views.get_reports, name='reports'),
    path('users/', views.get_registered_users, name='users'),
    path('dropout-summary',views.dropout_summary,name='dropout_summary'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('settings/', views.get_settings, name='settings'),
    path('categorized-students/', views.categorize_students, name='categorized_students'),
    path('edit-student/<int:student_id>', views.edit_student, name='edit_student'),
    path('logout/', views.logout_view, name='logout'),
    path('dropout-only',views.dropout_only,name='dropout-only'),
    path('dropout-rate/',views.rate,name='dropout-rate'),
    path('upload/', views.upload_image, name='upload_image'), 
    path('change_email',views.change_email,name='change-email'),
    path('change_phone',views.change_phone,name='change-phone'),
    path('account_delete',views.account_delete,name='account-delete'),
    path('account_delete/<int:id>/',views.account_delete,name='account-delete'),
    path('account_profile',views.profile,name='account_profile'),
    path('password-reset/', views.password_reset_request, name='password_reset'),
    path('change-password/', views.change_password, name='change_password'),
    path('change-password/done/', views.password_change_done, name='password_change_done'),
    path('password-reset-confirm/<uidb64>/<token>/', views.password_reset_confirm, name='password_reset_confirm'),
    path('password-reset-complete/', views.password_reset_complete, name='password_reset_complete'),


]